pipeline {
    agent any

    stages {
        stage('Mostrar usuario') {
            steps {
                echo "El usuario que inicio el trabajo es ${env.USERNAME}"
            }
        }
    }
}
